
import sys, json, random, zipfile
from pathlib import Path
from types import SimpleNamespace

import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
from torch_geometric.data import Data, Batch

inputs, source, save_root = map(Path, sys.argv[1:4])
sys.path.insert(0, str(source))
torch.set_num_threads(2)
assert torch.cuda.is_available()
device = "cuda"

# Compatibility with the original PANPooling import.
import torch_geometric.nn.pool.topk_pool as pool_module
from torch_geometric.nn.pool.select.topk import topk

def filter_adj(edge_index, edge_attr, perm, num_nodes=None):
    if num_nodes is None:
        num_nodes = int(edge_index.max()) + 1 if edge_index.numel() else len(perm)
    mapping = perm.new_full((num_nodes,), -1)
    mapping[perm] = torch.arange(len(perm), device=perm.device)
    row, col = mapping[edge_index[0]], mapping[edge_index[1]]
    keep = (row >= 0) & (col >= 0)
    return (
        torch.stack([row[keep], col[keep]]),
        edge_attr[keep] if edge_attr is not None else None,
    )

if not hasattr(pool_module, "topk"):
    pool_module.topk = topk
if not hasattr(pool_module, "filter_adj"):
    pool_module.filter_adj = filter_adj

from autoddi.model.gnn_model import GnnModel

folder = save_root / "seed_43"
folder.mkdir(exist_ok=True)

config = {
    "architecture": [5, 'SAGEConv', 'SAGEConv', 'TopKPool', 'global_max'],
    "seed": 43, "epochs": 30, "patience": 7, "min_delta": 0.0,
    "learning_rate": 0.001, "weight_decay": 0.0005,
    "max_pairs": 32, "edge_budget": 12000,
    "objective": "cross_entropy_84",
    "selection": "calibration_macro_f1_all84",
    "role": "final_training_from_scratch", "selected_candidate": 8,
    "controller_update_performed": False,
}

def atomic_save(obj, path):
    temporary = path.with_suffix(".tmp")
    torch.save(obj, temporary)
    temporary.replace(path)

import hashlib
def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()

config["train_sha256"] = digest(inputs / "train_pairs.csv")
config["cal_sha256"] = digest(inputs / "calibration_pairs.csv")


from importlib.metadata import version
config["environment"] = {
    name: version(name)
    for name in (
        "torch", "torch-geometric", "torch-scatter",
        "torch-sparse", "numpy", "scikit-learn"
    )
}
config["source_sha256"] = {
    str(p.relative_to(source)): digest(p)
    for p in sorted(source.rglob("*.py"))
}
config_path = folder / "config.json"

if config_path.exists():
    assert json.loads(config_path.read_text()) == config
else:
    config_path.write_text(json.dumps(config, indent=2))

train = pd.read_csv(inputs / "train_pairs.csv")
cal = pd.read_csv(inputs / "calibration_pairs.csv")
cols = ["drug1_id", "drug2_id", "label_id"]
train = train[cols].to_numpy(dtype=np.int64)
cal = cal[cols].to_numpy(dtype=np.int64)
assert len(train) == 78736 and len(cal) == 13894

random.seed(43)
np.random.seed(43)
torch.manual_seed(43)
torch.cuda.manual_seed_all(43)

model = GnnModel(
    config["architecture"], 55, 1, 84, "drugbank", hidden_dim=128
).to(device)
optimizer = torch.optim.Adam(
    model.parameters(), lr=0.001, weight_decay=0.0005
)

last = folder / "last_checkpoint.pt"
history, best, completed = [], -1., 0

if last.exists():
    # This checkpoint is generated by this script in your own Drive.
    state = torch.load(last, map_location="cpu", weights_only=False)
    assert state["config"] == config
    model.load_state_dict(state["model"])
    optimizer.load_state_dict(state["optimizer"])
    history, best, completed = (
        state["history"], state["best"], state["epoch"]
    )
    torch.set_rng_state(state["torch_rng"])
    torch.cuda.set_rng_state_all(state["cuda_rng"])
    print("Resuming after completed epoch:", completed, flush=True)

molecules = {}
if True:
    ids = sorted(set(np.concatenate([
        train[:, :2].ravel(), cal[:, :2].ravel()
    ]).tolist()))
    for i in ids:
        with np.load(
            inputs / "molecules" / f"{i:05d}.npz",
            allow_pickle=False,
        ) as d:
            molecules[i] = Data(
                x=torch.tensor(d["x"], dtype=torch.float32),
                edge_index=torch.tensor(d["edge_index"], dtype=torch.long),
            )

def batches(rows, shuffle, epoch):
    order = np.arange(len(rows))
    if shuffle:
        np.random.default_rng(43 + epoch).shuffle(order)
    group, cost = [], 0
    for i in order:
        a, b = rows[i, :2]
        size = molecules[a].num_nodes * molecules[b].num_nodes
        if group and (len(group) >= 32 or cost + size > 12000):
            yield rows[group]
            group, cost = [], 0
        group.append(i)
        cost += size
    if group:
        yield rows[group]

def forward(rows):
    hs = [molecules[int(i)].clone() for i in rows[:, 0]]
    ts = [molecules[int(i)].clone() for i in rows[:, 1]]
    edges, ho, to = [], 0, 0
    for h, t in zip(hs, ts):
        nh, nt = h.num_nodes, t.num_nodes
        edges.append(torch.stack([
            torch.arange(nh).repeat_interleave(nt) + ho,
            torch.arange(nt).repeat(nh) + to,
        ]))
        ho += nh
        to += nt

    h = Batch.from_data_list(hs).to(device)
    t = Batch.from_data_list(ts).to(device)
    graph = SimpleNamespace(edge_index=torch.cat(edges, 1).to(device))

    h.x = model.initial_norm(h.x, h.batch)
    t.x = model.initial_norm(t.x, t.batch)
    rh, rt = [], []
    for i, cell in enumerate(model.cells):
        h, t, a, b = cell(h, t, graph)
        rh.append(a)
        rt.append(b)
        h.x = F.elu(model.net_norms[i](h.x, h.batch))
        t.x = F.elu(model.net_norms[i](t.x, t.batch))

    heads, tails = torch.stack(rh, 1), torch.stack(rt, 1)
    head = model.post_processing
    relations = F.normalize(
        head.rel_emb.weight, dim=-1
    ).reshape(84, 128, 128)

    scores = torch.einsum(
        "bih,rhk->brik", F.normalize(heads, dim=-1), relations
    )
    scores = torch.einsum(
        "brik,bjk->brij", scores, F.normalize(tails, dim=-1)
    )
    logits = head.mlp(scores.reshape(-1, model.cells_num ** 2)).reshape(len(rows), 84)

    if not getattr(model, "_checked", False):
        with torch.no_grad():
            reference = head(
                heads.repeat_interleave(84, 0),
                tails.repeat_interleave(84, 0),
                torch.arange(84, device=device).repeat(len(rows)),
            ).reshape(len(rows), 84)
            torch.testing.assert_close(
                logits, reference, atol=1e-5, rtol=1e-4
            )
        model._checked = True
    return logits

from sklearn.metrics import f1_score


def epochs_without_improvement(records):
    if not records:
        return 0
    best_position = max(
        range(len(records)),
        key=lambda i: records[i]["cal_macro84"],
    )
    return int(records[-1]["epoch"] - records[best_position]["epoch"])


from sklearn.metrics import accuracy_score, f1_score
import shutil

summary_path = folder / "training_summary.json"
assert summary_path.is_file()
summary = json.loads(summary_path.read_text())

assert summary["seed"] == 43
assert summary["checkpoint_gap"] <= 1e-8
assert summary["completed_epochs"] == completed

best_path = folder / "best_checkpoint.pt"
checkpoint_hash_before = digest(best_path)

best_state = torch.load(
    best_path, map_location="cpu", weights_only=False
)
assert best_state["config"] == config
assert best_state["epoch"] == summary["best_epoch"]
assert abs(best_state["best"] - summary["best_cal_macro84"]) <= 1e-12

model.load_state_dict(best_state["model"], strict=True)
model.eval()

test_path = inputs / "test_pairs.csv"
test_df = pd.read_csv(test_path)
test = test_df[cols].to_numpy(dtype=np.int64)

assert len(test) == 17896
observed_labels = sorted(np.unique(test[:, 2]).tolist())
assert len(observed_labels) == 64
assert set(observed_labels).issubset(set(range(84)))

development_ids = set(train[:, :2].ravel()) | set(cal[:, :2].ravel())
test_ids = set(test[:, :2].ravel())
assert development_ids.isdisjoint(test_ids), "Test drug overlap detected."

print("\nCOLD TEST AUDIT", flush=True)
print("Rows:", len(test), flush=True)
print("Observed classes:", len(observed_labels), flush=True)
print("Test drugs:", len(test_ids), flush=True)
print("Development/Test drug overlap: 0", flush=True)
print("Best epoch:", best_state["epoch"], flush=True)

for drug_id in sorted(test_ids):
    with np.load(
        inputs / "molecules" / f"{int(drug_id):05d}.npz",
        allow_pickle=False,
    ) as saved:
        molecules[int(drug_id)] = Data(
            x=torch.tensor(saved["x"], dtype=torch.float32),
            edge_index=torch.tensor(
                saved["edge_index"], dtype=torch.long
            ),
        )

predictions = []
probability_batches = []
total_loss = 0.0

print("\nEvaluating Cold Test...", flush=True)

with torch.inference_mode():
    for step, rows in enumerate(batches(test, False, 0), 1):
        logits = forward(rows)
        assert torch.isfinite(logits).all()

        labels = torch.tensor(rows[:, 2], device=device)
        total_loss += F.cross_entropy(
            logits, labels, reduction="sum"
        ).item()

        probabilities = logits.softmax(dim=1)
        assert torch.isfinite(probabilities).all()

        predictions.extend(logits.argmax(1).cpu().tolist())
        probability_batches.append(probabilities.cpu().numpy())

        if step == 1 or step % 100 == 0:
            print(
                f"Test {len(predictions):,}/{len(test):,}",
                flush=True,
            )

assert len(predictions) == len(test)

predictions = np.asarray(predictions, dtype=np.int64)
probabilities = np.concatenate(probability_batches, axis=0)
assert probabilities.shape == (17896, 84)
np.testing.assert_allclose(
    probabilities.sum(axis=1), 1.0, rtol=1e-5, atol=1e-6
)

result = {
    "model": "AutoDDI_adapted",
    "protocol": "cold_both_drugs_unseen",
    "seed": 43,
    "selected_candidate": 8,
    "best_epoch": int(best_state["epoch"]),
    "completed_epochs": int(summary["completed_epochs"]),
    "cal_macro84": float(summary["best_cal_macro84"]),
    "checkpoint_gap": float(summary["checkpoint_gap"]),
    "test_rows": int(len(test)),
    "test_observed_classes": int(len(observed_labels)),
    "test_loss": float(total_loss / len(test)),
    "test_accuracy": float(accuracy_score(test[:, 2], predictions)),
    "test_macro64": float(f1_score(
        test[:, 2], predictions,
        labels=observed_labels,
        average="macro", zero_division=0,
    )),
    "test_macro84": float(f1_score(
        test[:, 2], predictions,
        labels=list(range(84)),
        average="macro", zero_division=0,
    )),
    "test_weighted_f1": float(f1_score(
        test[:, 2], predictions,
        labels=list(range(84)),
        average="weighted", zero_division=0,
    )),
    "test_evaluated": True,
    "test_pairs_sha256": digest(test_path),
    "best_checkpoint_sha256": checkpoint_hash_before,
}

# Save row-aligned predictions and probabilities.
output = test_df.copy()
output["predicted_label"] = predictions
output["prediction_confidence"] = probabilities.max(axis=1)

temporary = folder / "test_predictions.csv.tmp"
output.to_csv(temporary, index=False)
temporary.replace(folder / "test_predictions.csv")

temporary = folder / "test_probabilities.npz.tmp"
with temporary.open("wb") as file:
    np.savez_compressed(
        file,
        probabilities=probabilities,
        class_ids=np.arange(84, dtype=np.int64),
        drug1_id=test[:, 0],
        drug2_id=test[:, 1],
        y_true=test[:, 2],
        y_pred=predictions,
    )
temporary.replace(folder / "test_probabilities.npz")

temporary = folder / "final_result.csv.tmp"
pd.DataFrame([result]).to_csv(temporary, index=False)
temporary.replace(folder / "final_result.csv")

temporary = folder / "test_evaluation.json.tmp"
temporary.write_text(json.dumps(result, indent=2))
temporary.replace(folder / "test_evaluation.json")

# Verify that evaluation did not change the checkpoint.
assert digest(best_path) == checkpoint_hash_before

with np.load(folder / "test_probabilities.npz", allow_pickle=False) as saved:
    np.testing.assert_array_equal(saved["y_pred"], predictions)
    np.testing.assert_array_equal(saved["y_true"], test[:, 2])
    np.testing.assert_array_equal(saved["probabilities"], probabilities)

shutil.copy2(Path(__file__), folder / "evaluate_seed43.py")

zip_path = save_root / "AUTODDI_FINAL_SEED_43_EVALUATED.zip"
temporary_zip = save_root / "AUTODDI_FINAL_SEED_43_EVALUATED.tmp.zip"

print("\nCreating evaluated-seed backup...", flush=True)

with zipfile.ZipFile(
    temporary_zip, "w", zipfile.ZIP_DEFLATED, compresslevel=3
) as archive:
    for path in sorted(folder.iterdir()):
        if path.is_file() and not path.name.endswith(".tmp"):
            archive.write(path, arcname=f"seed_43/{path.name}")

with zipfile.ZipFile(temporary_zip) as archive:
    assert archive.testzip() is None

temporary_zip.replace(zip_path)

print("\n SEED 43 COLD TEST COMPLETED", flush=True)
print(json.dumps(result, indent=2), flush=True)
print("ZIP:", zip_path, flush=True)
print(" Checkpoint unchanged; saved predictions verified.", flush=True)
print(" No training. No Seed 44 started.", flush=True)
