
import sys, json, random, zipfile
from pathlib import Path
from types import SimpleNamespace

import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
from torch_geometric.data import Data, Batch

inputs, source, save_root = map(Path, sys.argv[1:4])
sys.path.insert(0, str(source))
torch.set_num_threads(2)
assert torch.cuda.is_available()
device = "cuda"

# Compatibility with the original PANPooling import.
import torch_geometric.nn.pool.topk_pool as pool_module
from torch_geometric.nn.pool.select.topk import topk

def filter_adj(edge_index, edge_attr, perm, num_nodes=None):
    if num_nodes is None:
        num_nodes = int(edge_index.max()) + 1 if edge_index.numel() else len(perm)
    mapping = perm.new_full((num_nodes,), -1)
    mapping[perm] = torch.arange(len(perm), device=perm.device)
    row, col = mapping[edge_index[0]], mapping[edge_index[1]]
    keep = (row >= 0) & (col >= 0)
    return (
        torch.stack([row[keep], col[keep]]),
        edge_attr[keep] if edge_attr is not None else None,
    )

if not hasattr(pool_module, "topk"):
    pool_module.topk = topk
if not hasattr(pool_module, "filter_adj"):
    pool_module.filter_adj = filter_adj

from autoddi.model.gnn_model import GnnModel

folder = save_root / "candidate_06"
folder.mkdir(exist_ok=True)

config = {
    "architecture": [3, 'GeneralConv', 'GCNConv', 'PANPool', 'global_add'],
    "seed": 42, "epochs": 5,
    "learning_rate": 0.001, "weight_decay": 0.0005,
    "max_pairs": 32, "edge_budget": 12000,
    "objective": "cross_entropy_84",
    "selection": "calibration_macro_f1_all84",
    "role": "sampled_from_reconstructed_controller",
    "controller_update_performed": False,
}

def atomic_save(obj, path):
    temporary = path.with_suffix(".tmp")
    torch.save(obj, temporary)
    temporary.replace(path)

import hashlib
def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()

config["train_sha256"] = digest(inputs / "train_pairs.csv")
config["cal_sha256"] = digest(inputs / "calibration_pairs.csv")

config_path = folder / "config.json"
if config_path.exists():
    assert json.loads(config_path.read_text()) == config
else:
    config_path.write_text(json.dumps(config, indent=2))

train = pd.read_csv(inputs / "train_pairs.csv")
cal = pd.read_csv(inputs / "calibration_pairs.csv")
cols = ["drug1_id", "drug2_id", "label_id"]
train = train[cols].to_numpy(dtype=np.int64)
cal = cal[cols].to_numpy(dtype=np.int64)
assert len(train) == 78736 and len(cal) == 13894

random.seed(42)
np.random.seed(42)
torch.manual_seed(42)
torch.cuda.manual_seed_all(42)

model = GnnModel(
    config["architecture"], 55, 1, 84, "drugbank", hidden_dim=128
).to(device)
optimizer = torch.optim.Adam(
    model.parameters(), lr=0.001, weight_decay=0.0005
)

last = folder / "last_checkpoint.pt"
history, best, completed = [], -1., 0

if last.exists():
    # This checkpoint is generated by this script in your own Drive.
    state = torch.load(last, map_location="cpu", weights_only=False)
    assert state["config"] == config
    model.load_state_dict(state["model"])
    optimizer.load_state_dict(state["optimizer"])
    history, best, completed = (
        state["history"], state["best"], state["epoch"]
    )
    torch.set_rng_state(state["torch_rng"])
    torch.cuda.set_rng_state_all(state["cuda_rng"])
    print("Resuming after completed epoch:", completed, flush=True)

molecules = {}
if completed < 5:
    ids = sorted(set(np.concatenate([
        train[:, :2].ravel(), cal[:, :2].ravel()
    ]).tolist()))
    for i in ids:
        with np.load(
            inputs / "molecules" / f"{i:05d}.npz",
            allow_pickle=False,
        ) as d:
            molecules[i] = Data(
                x=torch.tensor(d["x"], dtype=torch.float32),
                edge_index=torch.tensor(d["edge_index"], dtype=torch.long),
            )

def batches(rows, shuffle, epoch):
    order = np.arange(len(rows))
    if shuffle:
        np.random.default_rng(42 + epoch).shuffle(order)
    group, cost = [], 0
    for i in order:
        a, b = rows[i, :2]
        size = molecules[a].num_nodes * molecules[b].num_nodes
        if group and (len(group) >= 32 or cost + size > 12000):
            yield rows[group]
            group, cost = [], 0
        group.append(i)
        cost += size
    if group:
        yield rows[group]

def forward(rows):
    hs = [molecules[int(i)].clone() for i in rows[:, 0]]
    ts = [molecules[int(i)].clone() for i in rows[:, 1]]
    edges, ho, to = [], 0, 0
    for h, t in zip(hs, ts):
        nh, nt = h.num_nodes, t.num_nodes
        edges.append(torch.stack([
            torch.arange(nh).repeat_interleave(nt) + ho,
            torch.arange(nt).repeat(nh) + to,
        ]))
        ho += nh
        to += nt

    h = Batch.from_data_list(hs).to(device)
    t = Batch.from_data_list(ts).to(device)
    graph = SimpleNamespace(edge_index=torch.cat(edges, 1).to(device))

    h.x = model.initial_norm(h.x, h.batch)
    t.x = model.initial_norm(t.x, t.batch)
    rh, rt = [], []
    for i, cell in enumerate(model.cells):
        h, t, a, b = cell(h, t, graph)
        rh.append(a)
        rt.append(b)
        h.x = F.elu(model.net_norms[i](h.x, h.batch))
        t.x = F.elu(model.net_norms[i](t.x, t.batch))

    heads, tails = torch.stack(rh, 1), torch.stack(rt, 1)
    head = model.post_processing
    relations = F.normalize(
        head.rel_emb.weight, dim=-1
    ).reshape(84, 128, 128)

    scores = torch.einsum(
        "bih,rhk->brik", F.normalize(heads, dim=-1), relations
    )
    scores = torch.einsum(
        "brik,bjk->brij", scores, F.normalize(tails, dim=-1)
    )
    logits = head.mlp(scores.reshape(-1, model.cells_num ** 2)).reshape(len(rows), 84)

    if not getattr(model, "_checked", False):
        with torch.no_grad():
            reference = head(
                heads.repeat_interleave(84, 0),
                tails.repeat_interleave(84, 0),
                torch.arange(84, device=device).repeat(len(rows)),
            ).reshape(len(rows), 84)
            torch.testing.assert_close(
                logits, reference, atol=1e-5, rtol=1e-4
            )
        model._checked = True
    return logits

from sklearn.metrics import f1_score

for epoch in range(completed + 1, 6):
    model.train()
    total, seen = 0., 0
    for step, rows in enumerate(batches(train, True, epoch), 1):
        optimizer.zero_grad(set_to_none=True)
        logits = forward(rows)
        y = torch.tensor(rows[:, 2], device=device)
        loss = F.cross_entropy(logits, y)
        assert torch.isfinite(loss)
        loss.backward()
        for p in model.parameters():
            if p.grad is not None:
                assert torch.isfinite(p.grad).all()
        optimizer.step()
        total += loss.item() * len(rows)
        seen += len(rows)
        if step == 1 or step % 100 == 0:
            print(
                f"Epoch {epoch}/5 | Train {seen:,}/78,736 "
                f"| Loss={total/seen:.5f}", flush=True
            )
    assert seen == len(train)

    model.eval()
    predictions = []
    with torch.no_grad():
        for step, rows in enumerate(batches(cal, False, epoch), 1):
            logits = forward(rows)
            assert torch.isfinite(logits).all()
            predictions.extend(logits.argmax(1).cpu().tolist())
            if step == 1 or step % 100 == 0:
                print(
                    f"Calibration {len(predictions):,}/13,894",
                    flush=True,
                )
    assert len(predictions) == len(cal)
    score = float(f1_score(
        cal[:, 2], predictions, labels=list(range(84)),
        average="macro", zero_division=0,
    ))
    improved = score > best
    best = max(best, score)
    history.append({
        "epoch": epoch, "train_loss": total/seen,
        "cal_macro84": score,
    })

    state = {
        "config": config, "epoch": epoch,
        "model": model.state_dict(),
        "optimizer": optimizer.state_dict(),
        "history": history, "best": best,
        "torch_rng": torch.get_rng_state(),
        "cuda_rng": torch.cuda.get_rng_state_all(),
    }

    # Save best before last so a failed save does not advance resume state.
    if improved:
        atomic_save(state, folder / "best_checkpoint.pt")
    atomic_save(state, last)
    pd.DataFrame(history).to_csv(folder / "history.csv", index=False)

    print(
        f" Epoch {epoch} saved to Drive | "
        f"CAL Macro84={score:.6f} | Best={best:.6f}",
        flush=True,
    )

result = {
    "candidate": 6,
    "architecture": config["architecture"],
    "best_cal_macro84": best,
    "completed_epochs": 5,
    "test_evaluated": False,
    "controller_updated": False,
}
(folder / "result.json").write_text(json.dumps(result, indent=2))

# Include the runner so the checkpoint is usable after a session reset.
import shutil
shutil.copy2(Path(__file__), folder / "run_candidate_06.py")


for filename in (
    "controller_after_candidate_05.pt",
    "candidate_06_selection.json",
    "prepare_candidate_06.py",
):
    shutil.copy2(save_root / filename, folder / filename)

zip_path = save_root / "AUTODDI_CANDIDATE_06_COMPLETE.zip"
temporary_zip = save_root / "AUTODDI_CANDIDATE_06_COMPLETE.tmp.zip"
with zipfile.ZipFile(
    temporary_zip, "w", zipfile.ZIP_DEFLATED, compresslevel=3
) as z:
    for p in sorted(folder.iterdir()):
        if p.is_file() and p.suffix != ".tmp":
            z.write(p, arcname=f"candidate_06/{p.name}")
with zipfile.ZipFile(temporary_zip) as z:
    assert z.testzip() is None
temporary_zip.replace(zip_path)

print("\n ONE CANDIDATE COMPLETED — STOPPED", flush=True)
print("Best CAL Macro84:", best, flush=True)
print("ZIP on Drive:", zip_path, flush=True)
print("No test evaluation. This runner does not launch another candidate.", flush=True)
