
import sys, json, random, zipfile
from pathlib import Path
from types import SimpleNamespace

import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
from torch_geometric.data import Data, Batch

inputs, source, save_root = map(Path, sys.argv[1:4])
sys.path.insert(0, str(source))
torch.set_num_threads(2)
assert torch.cuda.is_available()
device = "cuda"

# Compatibility with the original PANPooling import.
import torch_geometric.nn.pool.topk_pool as pool_module
from torch_geometric.nn.pool.select.topk import topk

def filter_adj(edge_index, edge_attr, perm, num_nodes=None):
    if num_nodes is None:
        num_nodes = int(edge_index.max()) + 1 if edge_index.numel() else len(perm)
    mapping = perm.new_full((num_nodes,), -1)
    mapping[perm] = torch.arange(len(perm), device=perm.device)
    row, col = mapping[edge_index[0]], mapping[edge_index[1]]
    keep = (row >= 0) & (col >= 0)
    return (
        torch.stack([row[keep], col[keep]]),
        edge_attr[keep] if edge_attr is not None else None,
    )

if not hasattr(pool_module, "topk"):
    pool_module.topk = topk
if not hasattr(pool_module, "filter_adj"):
    pool_module.filter_adj = filter_adj

from autoddi.model.gnn_model import GnnModel

folder = save_root / "seed_44"
folder.mkdir(exist_ok=True)

config = {
    "architecture": [5, 'SAGEConv', 'SAGEConv', 'TopKPool', 'global_max'],
    "seed": 44, "epochs": 30, "patience": 7, "min_delta": 0.0,
    "learning_rate": 0.001, "weight_decay": 0.0005,
    "max_pairs": 32, "edge_budget": 12000,
    "objective": "cross_entropy_84",
    "selection": "calibration_macro_f1_all84",
    "role": "final_training_from_scratch", "selected_candidate": 8,
    "controller_update_performed": False,
}

def atomic_save(obj, path):
    temporary = path.with_suffix(".tmp")
    torch.save(obj, temporary)
    temporary.replace(path)

import hashlib
def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()

config["train_sha256"] = digest(inputs / "train_pairs.csv")
config["cal_sha256"] = digest(inputs / "calibration_pairs.csv")


from importlib.metadata import version
config["environment"] = {
    name: version(name)
    for name in (
        "torch", "torch-geometric", "torch-scatter",
        "torch-sparse", "numpy", "scikit-learn"
    )
}
config["source_sha256"] = {
    str(p.relative_to(source)): digest(p)
    for p in sorted(source.rglob("*.py"))
}
config_path = folder / "config.json"

if config_path.exists():
    assert json.loads(config_path.read_text()) == config
else:
    config_path.write_text(json.dumps(config, indent=2))

train = pd.read_csv(inputs / "train_pairs.csv")
cal = pd.read_csv(inputs / "calibration_pairs.csv")
cols = ["drug1_id", "drug2_id", "label_id"]
train = train[cols].to_numpy(dtype=np.int64)
cal = cal[cols].to_numpy(dtype=np.int64)
assert len(train) == 78736 and len(cal) == 13894

random.seed(44)
np.random.seed(44)
torch.manual_seed(44)
torch.cuda.manual_seed_all(44)

model = GnnModel(
    config["architecture"], 55, 1, 84, "drugbank", hidden_dim=128
).to(device)
optimizer = torch.optim.Adam(
    model.parameters(), lr=0.001, weight_decay=0.0005
)

last = folder / "last_checkpoint.pt"
history, best, completed = [], -1., 0

if last.exists():
    # This checkpoint is generated by this script in your own Drive.
    state = torch.load(last, map_location="cpu", weights_only=False)
    assert state["config"] == config
    model.load_state_dict(state["model"])
    optimizer.load_state_dict(state["optimizer"])
    history, best, completed = (
        state["history"], state["best"], state["epoch"]
    )
    torch.set_rng_state(state["torch_rng"])
    torch.cuda.set_rng_state_all(state["cuda_rng"])
    print("Resuming after completed epoch:", completed, flush=True)

molecules = {}
if True:
    ids = sorted(set(np.concatenate([
        train[:, :2].ravel(), cal[:, :2].ravel()
    ]).tolist()))
    for i in ids:
        with np.load(
            inputs / "molecules" / f"{i:05d}.npz",
            allow_pickle=False,
        ) as d:
            molecules[i] = Data(
                x=torch.tensor(d["x"], dtype=torch.float32),
                edge_index=torch.tensor(d["edge_index"], dtype=torch.long),
            )

def batches(rows, shuffle, epoch):
    order = np.arange(len(rows))
    if shuffle:
        np.random.default_rng(44 + epoch).shuffle(order)
    group, cost = [], 0
    for i in order:
        a, b = rows[i, :2]
        size = molecules[a].num_nodes * molecules[b].num_nodes
        if group and (len(group) >= 32 or cost + size > 12000):
            yield rows[group]
            group, cost = [], 0
        group.append(i)
        cost += size
    if group:
        yield rows[group]

def forward(rows):
    hs = [molecules[int(i)].clone() for i in rows[:, 0]]
    ts = [molecules[int(i)].clone() for i in rows[:, 1]]
    edges, ho, to = [], 0, 0
    for h, t in zip(hs, ts):
        nh, nt = h.num_nodes, t.num_nodes
        edges.append(torch.stack([
            torch.arange(nh).repeat_interleave(nt) + ho,
            torch.arange(nt).repeat(nh) + to,
        ]))
        ho += nh
        to += nt

    h = Batch.from_data_list(hs).to(device)
    t = Batch.from_data_list(ts).to(device)
    graph = SimpleNamespace(edge_index=torch.cat(edges, 1).to(device))

    h.x = model.initial_norm(h.x, h.batch)
    t.x = model.initial_norm(t.x, t.batch)
    rh, rt = [], []
    for i, cell in enumerate(model.cells):
        h, t, a, b = cell(h, t, graph)
        rh.append(a)
        rt.append(b)
        h.x = F.elu(model.net_norms[i](h.x, h.batch))
        t.x = F.elu(model.net_norms[i](t.x, t.batch))

    heads, tails = torch.stack(rh, 1), torch.stack(rt, 1)
    head = model.post_processing
    relations = F.normalize(
        head.rel_emb.weight, dim=-1
    ).reshape(84, 128, 128)

    scores = torch.einsum(
        "bih,rhk->brik", F.normalize(heads, dim=-1), relations
    )
    scores = torch.einsum(
        "brik,bjk->brij", scores, F.normalize(tails, dim=-1)
    )
    logits = head.mlp(scores.reshape(-1, model.cells_num ** 2)).reshape(len(rows), 84)

    if not getattr(model, "_checked", False):
        with torch.no_grad():
            reference = head(
                heads.repeat_interleave(84, 0),
                tails.repeat_interleave(84, 0),
                torch.arange(84, device=device).repeat(len(rows)),
            ).reshape(len(rows), 84)
            torch.testing.assert_close(
                logits, reference, atol=1e-5, rtol=1e-4
            )
        model._checked = True
    return logits

from sklearn.metrics import f1_score


def epochs_without_improvement(records):
    if not records:
        return 0
    best_position = max(
        range(len(records)),
        key=lambda i: records[i]["cal_macro84"],
    )
    return int(records[-1]["epoch"] - records[best_position]["epoch"])

for epoch in range(completed + 1, config["epochs"] + 1):
    if epochs_without_improvement(history) >= config["patience"]:
        print("Early stopping already reached.", flush=True)
        break

    model.train()
    total, seen = 0., 0
    for step, rows in enumerate(batches(train, True, epoch), 1):
        optimizer.zero_grad(set_to_none=True)
        logits = forward(rows)
        y = torch.tensor(rows[:, 2], device=device)
        loss = F.cross_entropy(logits, y)
        assert torch.isfinite(loss)
        loss.backward()
        for p in model.parameters():
            if p.grad is not None:
                assert torch.isfinite(p.grad).all()
        optimizer.step()
        total += loss.item() * len(rows)
        seen += len(rows)
        if step == 1 or step % 100 == 0:
            print(
                f"Epoch {epoch}/{config['epochs']} | Train {seen:,}/78,736 "
                f"| Loss={total/seen:.5f}", flush=True
            )
    assert seen == len(train)

    model.eval()
    predictions = []
    with torch.no_grad():
        for step, rows in enumerate(batches(cal, False, epoch), 1):
            logits = forward(rows)
            assert torch.isfinite(logits).all()
            predictions.extend(logits.argmax(1).cpu().tolist())
            if step == 1 or step % 100 == 0:
                print(
                    f"Calibration {len(predictions):,}/13,894",
                    flush=True,
                )
    assert len(predictions) == len(cal)
    score = float(f1_score(
        cal[:, 2], predictions, labels=list(range(84)),
        average="macro", zero_division=0,
    ))
    improved = score > best
    best = max(best, score)
    history.append({
        "epoch": epoch, "train_loss": total/seen,
        "cal_macro84": score,
    })

    state = {
        "config": config, "epoch": epoch,
        "model": model.state_dict(),
        "optimizer": optimizer.state_dict(),
        "history": history, "best": best,
        "torch_rng": torch.get_rng_state(),
        "cuda_rng": torch.cuda.get_rng_state_all(),
    }

    # Save best before last so a failed save does not advance resume state.
    if improved:
        atomic_save(state, folder / "best_checkpoint.pt")
    atomic_save(state, last)
    history_tmp = folder / "history.csv.tmp"
    pd.DataFrame(history).to_csv(history_tmp, index=False)
    history_tmp.replace(folder / "history.csv")

    print(
        f" Epoch {epoch} saved to Working | "
        f"CAL Macro84={score:.6f} | Best={best:.6f}",
        flush=True,
    )


# Restore and independently re-evaluate the best checkpoint on Calibration.
best_state = torch.load(
    folder / "best_checkpoint.pt",
    map_location="cpu",
    weights_only=False,
)
assert best_state["config"] == config
model.load_state_dict(best_state["model"])
model.eval()

predictions = []
print("\nAuditing best checkpoint on Calibration...", flush=True)

with torch.no_grad():
    for step, rows in enumerate(batches(cal, False, 0), 1):
        logits = forward(rows)
        assert torch.isfinite(logits).all()
        predictions.extend(logits.argmax(1).cpu().tolist())

        if step == 1 or step % 100 == 0:
            print(
                f"Calibration audit {len(predictions):,}/{len(cal):,}",
                flush=True,
            )

assert len(predictions) == len(cal)

reloaded_score = float(f1_score(
    cal[:, 2], predictions,
    labels=list(range(84)),
    average="macro",
    zero_division=0,
))
saved_score = float(best_state["best"])
gap = abs(reloaded_score - saved_score)
assert gap <= 1e-8, f"Checkpoint audit failed: gap={gap}"

# Refresh CSV from checkpoint-backed history if resuming after a partial write.
history_tmp = folder / "history.csv.tmp"
pd.DataFrame(history).to_csv(history_tmp, index=False)
history_tmp.replace(folder / "history.csv")

cal_output = pd.DataFrame(
    cal, columns=["drug1_id", "drug2_id", "label_id"]
)
cal_output["predicted_label"] = predictions
cal_output.to_csv(folder / "calibration_predictions.csv", index=False)

summary = {
    "model": "AutoDDI_adapted",
    "seed": config["seed"],
    "architecture": config["architecture"],
    "selected_candidate": 8,
    "completed_epochs": int(history[-1]["epoch"]),
    "best_epoch": int(best_state["epoch"]),
    "best_cal_macro84": saved_score,
    "reloaded_cal_macro84": reloaded_score,
    "checkpoint_gap": gap,
    "early_stopped": (
        epochs_without_improvement(history) >= config["patience"]
    ),
    "test_evaluated": False,
}
summary_tmp = folder / "training_summary.json.tmp"
summary_tmp.write_text(json.dumps(summary, indent=2))
summary_tmp.replace(folder / "training_summary.json")

# Package this seed's checkpoints, configuration, history and runner.
zip_path = save_root / "AUTODDI_FINAL_SEED_44_TRAINED.zip"
temporary_zip = save_root / "AUTODDI_FINAL_SEED_44_TRAINED.tmp.zip"

print("\nCreating training backup...", flush=True)
with zipfile.ZipFile(
    temporary_zip, "w", zipfile.ZIP_DEFLATED, compresslevel=3
) as archive:
    for path in sorted(folder.iterdir()):
        if path.is_file() and not path.name.endswith(".tmp"):
            archive.write(path, arcname=f"seed_44/{path.name}")

with zipfile.ZipFile(temporary_zip) as archive:
    assert archive.testzip() is None
temporary_zip.replace(zip_path)

print("\n SEED 44 FINAL TRAINING COMPLETED", flush=True)
print(json.dumps(summary, indent=2), flush=True)
print("ZIP:", zip_path, flush=True)
print(" No Test evaluation. No additional seed started.", flush=True)
